name: responsive_size_helper_plus
description: A Flutter package for creating responsive layouts by converting Figma dimensions to device-specific sizes across all platforms.
version: 1.0.5
homepage: https://github.com/mamipro-123/responsive_size_helper_plus
repository: https://github.com/mamipro-123/responsive_size_helper_plus
issue_tracker: https://github.com/mamipro-123/responsive_size_helper_plus/issues
documentation: https://github.com/mamipro-123/responsive_size_helper_plus/blob/main/README.md

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - responsive
  - ui
  - layout
  - design
  - figma

funding:
  - https://github.com/sponsors/mamipro-123 